#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          soundjack
# Required-Start:    $syslog $local_fs $remote_fs
# Required-Stop:     $syslog $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: soundjack
# Description:       soundjack
### END INIT INFO

export PATH=/root/dev/SoundjackLinux:$PATH
export DISPLAY=:100

case "$1" in
	start)
		echo "Starting soundjack"
		/root/dev/SoundjackLinux/sj-wrapper.sh start
		;;

	stop)
		echo "Stopping soundjack"
		/root/dev/SoundjackLinux/sj-wrapper.sh stop
		;;

	restart)
		echo "Restarting soundjack"
		$0 stop
		$0 start
		;;

	*)
		echo "Script supports start/stop/restart"
		exit 1
		;;
esac
